name: Close AI-flagged spam after grace
on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  janitor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            const { owner, repo } = context.repo;
            const LABEL = 'ai:pr-spam:yes';             // label added by your AI step
            const EXEMPT = ['triaged:accepted','do-not-close'];
            const GRACE_MIN = 720;

            // List open items with the AI label (PRs are issues under the hood)
            const items = await github.paginate(github.rest.issues.listForRepo, {
              owner, repo, state: 'open', labels: LABEL, per_page: 100
            });

            for (const it of items.filter(i => i.pull_request)) {
              // Skip if exempted
              if (it.labels.some(l => EXEMPT.includes(l.name))) continue;

              // When was LABEL applied?
              const events = await github.paginate(github.rest.issues.listEvents, {
                owner, repo, issue_number: it.number, per_page: 100
              });
              const labeled = events.reverse().find(e =>
                e.event === 'labeled' && e.label && e.label.name === LABEL
              );
              const labeledAt = labeled ? new Date(labeled.created_at) : new Date(it.updated_at);
              const ageMin = (Date.now() - labeledAt.getTime()) / 60000;

              if (ageMin >= GRACE_MIN) {
                const msg = `Auto-closing after ${GRACE_MIN} min grace for label \`${LABEL}\`. ` +
                            `If this was a mistake, a maintainer can remove the label and reopen.`;
                await github.rest.issues.createComment({ owner, repo, issue_number: it.number, body: msg });
                await github.rest.pulls.update({ owner, repo, pull_number: it.number, state: 'closed' });
              }
            }